/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      danger: "var(--color-danger)",
      "danger-foreground": "var(--color-danger-foreground)",
      warning: "var(--color-warning)",
      "warning-foreground": "var(--color-warning-foreground)",
      info: "var(--color-info)",
      "info-foreground": "var(--color-info-foreground)",
      success: "var(--color-success)",
      "success-foreground": "var(--color-success-foreground)",

      primary: {
        150: "var(--primary-150)",
        "150-foreground": "var(--primary-150-foreground)",
        125: "var(--primary-125)",
        "125-foreground": "var(--primary-125-foreground)",
        100: "var(--primary-100)",
        "100-foreground": "var(--primary-100-foreground)",
        75: "var(--primary-75)",
        "75-foreground": "var(--primary-75-foreground)",
        50: "var(--primary-50)",
        "50-foreground": "var(--primary-50-foreground)",
        25: "var(--primary-25)",
        "25-foreground": "var(--primary-25-foreground)",
      },

      tertiary: {
        150: "var(--tertiary-150)",
        "150-foreground": "var(--tertiary-150-foreground)",
        125: "var(--tertiary-125)",
        "125-foreground": "var(--tertiary-125-foreground)",
        100: "var(--tertiary-100)",
        "100-foreground": "var(--tertiary-100-foreground)",
        75: "var(--tertiary-75)",
        "75-foreground": "var(--tertiary-75-foreground)",
        50: "var(--tertiary-50)",
        "50-foreground": "var(--tertiary-50-foreground)",
        25: "var(--tertiary-25)",
        "25-foreground": "var(--tertiary-25-foreground)",
      },

      secondary: {
        150: "var(--secondary-150)",
        "150-foreground": "var(--secondary-150-foreground)",
        125: "var(--secondary-125)",
        "125-foreground": "var(--secondary-125-foreground)",
        100: "var(--secondary-100)",
        "100-foreground": "var(--secondary-100-foreground)",
        75: "var(--secondary-75)",
        "75-foreground": "var(--secondary-75-foreground)",
        50: "var(--secondary-50)",
        "50-foreground": "var(--secondary-50-foreground)",
        25: "var(--secondary-25)",
        "25-foreground": "var(--secondary-25-foreground)",
      },

      accent: {
        150: "var(--accent-150)",
        "150-foreground": "var(--accent-150-foreground)",
        125: "var(--accent-125)",
        "125-foreground": "var(--accent-125-foreground)",
        100: "var(--accent-100)",
        "100-foreground": "var(--accent-100-foreground)",
        75: "var(--accent-75)",
        "75-foreground": "var(--accent-75-foreground)",
        50: "var(--accent-50)",
        "50-foreground": "var(--accent-50-foreground)",
        25: "var(--accent-25)",
        "25-foreground": "var(--accent-25-foreground)",
      },
    },
  },
  plugins: [],
};
