# Generated by Django 5.1.5 on 2025-03-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercredential",
            name="password",
            field=models.BinaryField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usercredential",
            name="salt",
            field=models.BinaryField(max_length=100),
        ),
    ]
