services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mesdev_db
      MYSQL_USER: mesdev
      MYSQL_PASSWORD: mesdev
    volumes:
      - mesdev-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  mesdev-db-data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
